### PR TITLE
chore: 🤖 upgrade to angular v18

### PR DESCRIPTION
**Pull request by chimurai**
(new PR without `npm install --force`)

- Upgraded Nx incrementally between major Nx versions.
- See commit body for details

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] Other... Please describe: Angular version update

## What is the current behavior?

Angular 17

Issue Number: N/A

## What is the new behavior?

Angular 18

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by shaharkazaz** [comment]
Why is this marked as a breaking change? Nothing is actually affected

**Comment by chimurai** [comment]
You're right.
Removed the "breaking change" from commit body and PR description

**Comment by shaharkazaz** [comment]
I ran yesterday the upgrade as well, but I did nx 17 -> 18 -> 19 instead of the latest directly, and I didn't get all these changes in the `project.json` files which makes me wonder which version is the correct one and why I didn't get those changes. 
I ran the migrations between each step of course.
Any idea?

**Comment by chimurai** [comment]
Hmmm... Indeed, I don't see `project.json` changes with intermediate upgrades.

Found Nx's recommendation on upgrades:
> One major version at a time, small steps
https://nx.dev/recipes/tips-n-tricks/advanced-update#recommendations

I'll revert the commits and rebase this branch with intermediate upgrades

**Comment by shaharkazaz** [comment]
Yep, that's what I did 😄

**Comment by chimurai** [comment]
Much better now without `project.json` changes 😄

**Pull request merged**
