### PR TITLE
chore: 🤖 upgrade to nx17

### PR DESCRIPTION
**Pull request by alexdabast**
Upgrading to nx17 using npx nx migrate latest

✅ Closes: #731

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ x] Other... Please describe:
Nx upgrade version

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information
I did not manually bump any devPeer in libs folder as I don't think it is required to do that

### CODE REVIEW

**Comment by alexdabast** [comment]
@shaharkazaz I will look into the tests failing
however what do you mean by migration the playground ?
It looks to me that the playground is using angular 17 as you can use the new syntaxe for example and it is working fine
image

and the code
image

**Comment by alexdabast** [comment]
@shaharkazaz I have run the migration and did some test seems ok
Regarding the lint and test now angular workspace are by default standalone so I force the workspace creation to standalone:false and removed the standalone:true on the standalone test.

Also had to replace runSchematicAsync by runSchematic and remove the conversion to promise as it returns now directly a promise

**Comment by shaharkazaz** [comment]
1. **Lint:**  Please set `@typescript-eslint/no-explicit-any` as a warning and not an error, and remove all the unused var cases, that should take care of that.
2. **Tests:** Seems like a beforeAll hook is failing, try to run it locally and debug the issue, any chance you need to update from master?

**Comment by theguidingstar** [comment]
Any news on this?
When it's going to be merged and released?

**Comment by jontze** [comment]
Thanks for your work on this PR, @alexdabast. Do you still have the time to push this forward? 

If not, I would be happy to support you in completing the remaining points :)

**Comment by shaharkazaz** [comment]
The repository is already using nx v17

**Pull request closed without merging**
